user_user:
    resource: "@UserBundle/Controller/UserController.php"
    type:     annotation

image:
    resource: "@ImageBundle/Controller/"
    type:     annotation
    prefix:   /

article:
    resource: "@ArticleBundle/Controller/"
    type:     annotation
    prefix:   /

forum:
    resource: "@ForumBundle/Controller/"
    type:     annotation
    prefix:   /

war:
    resource: "@WarBundle/Controller/"
    type:     annotation
    prefix:   /

team:
    resource: "@TeamBundle/Controller/"
    type:     annotation
    prefix:   /

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /
userBundle_admin:
    path: /admin
    defaults: { _controller: UserBundle:Admin:index}
logout:
    path: /logout

